---
title: "Polygon Layer: Vancouver Blocks"
---

See also: [deck.gl Example](https://deck.gl/#/examples/core-layers/geojson-layer-polygons)

```{r message = FALSE, warning = FALSE}
library(sf)
library(deckgl)

vancouver_blocks <- readRDS("../data/vancouver-blocks.rds") %>%
    dplyr::mutate(
      elevation = sqrt(valuePerSqm) * 10,
      growth = round(growth * 100)
    )

pal <- scales::col_bin("Oranges", domain = seq(-0.6, 1.2, 0.15) * 100, bins = 12)
vancouver_blocks$color <- pal(vancouver_blocks$growth)

initial_view_state <- list(
  latitude = 49.254,
  longitude = -123.13,
  zoom = 11,
  maxZoom = 16,
  pitch = 45,
  bearing = 0
)

deckgl(
  width = "100%", height = "600px",
  initial_view_state = initial_view_state#,
  #style = list(background = "#c6e1f7")
  #style = list(background = "none")
) %>%
  #add_control("Polygon Layer") %>%
  #add_control('Press "e" to toggle JSON editor.') %>%
  add_polygon_layer(
    data = vancouver_blocks,
    extruded = TRUE,
    opacity = 0.8,
    stroked = FALSE,
    getPolygon = ~geometry,
    getFillColor = ~color,
    getElevation = ~elevation,
    wireframe = TRUE,
    getLineColor = "white",
    tooltip = paste0(
      "<div>Average Property Value: ${{valuePerSqm}} / m<sup>2</sup></div>",
      "<div>Growth: {{growth}}%</div>"
    )
  ) %>%
  add_json_editor(style = "display: none;")
```

```{r data}
vancouver_blocks %>%
  head()
```

Data source: [City of Vancouver](http://data.vancouver.ca/)